### ISSUE TITLE
 About ae2 in 2.7.0 when playing normal mode

### ISSUE THREAD

**Issue by Fubuki007** [ZZZank/Enlightened6#13]
![sdsds](https://github.com/user-attachments/assets/c1a00724-68cb-472f-b719-bec46d66cea7)
Without the Si from ae2 when you make Si board.
The only synthesizable formula can't be used in AE2

**Comment by Fubuki007** [comment]
@ZZZank 
![屏幕截图 2024-08-28 161643](https://github.com/user-attachments/assets/a9535f6e-ee48-4eef-af60-5b8cb7a24315)

**Comment by ZZZank** [comment]
This can be because AE2 is adding recipe ingredients in a non-standard way, but it will take me some time to investigate into it.

Before a new version released, you can try `Oredictionificator` from Mekanism or other machines that can convert items in the same tags to convert EE silicon into AE silicon, as a workaround

**Comment by Fubuki007** [comment]
I used oredictionificator,but it seemed didn't work T T
I surely know that how to use this machine.

**Comment by Fubuki007** [comment]
Not found the tablet.

**Comment by ZZZank** [comment]
well, this is because Oredictionificator only allows several predefined tags. There are two solutions to this:
1. copy codes below, and goto `kubejs/server_scripts`, create a new .txt file and rename it to `temp_ae_silicon_fix.js` (mind the suffix must change from `.txt` to `.js`), and paste codes into it:
```js
onEvent('recipes', (event) => {
    if (global.isExpertMode) {
        return;
    }
    event
        .custom({
            type: 'appliedenergistics2:inscriber',
            mode: 'inscribe',
            ingredients: {
                top: toJsonWithCount('appliedenergistics2:silicon_press'),
                middle: toJsonWithCount('emendatusenigmatica:silicon_gem')
            },
            result: toJsonWithCount('appliedenergistics2:printed_silicon')
        })
        .id('appliedenergistics2:inscriber/silicon_print');
});
```
this will replace the existing inscriber recipe with a new recipe where you can use EE silicon for inscribing
2. or open `config/Mekanism/general.toml`, locate a line that starts with `validItemFilters =` (usually the last line), add `, "forge:silicon"` into the list. After modifying, it should look like this:
```toml
	#Oredictionificator Settings
	[general.oredictionificator]
		#The list of valid tag prefixes for the Oredictionificator. Note: It is highly recommended to only include well known/defined tag prefixes otherwise it is very easy to potentially add in accidental conversions of things that are not actually equivalent.
		validItemFilters = ["forge:dusts/", "forge:ingots/", "forge:nuggets/", "forge:ores/", "forge:storage_blocks/", "forge:silicon"]
```
you can see `"forge:silicon"` in the list
After this, you will be able to convert silicons via `Oredictionificator`

Both of the two options require your game closed to prevent problems
